### ISSUE TITLE
Uncaught TypeError: e.addClass is not a function

### ISSUE THREAD

**Issue by andreheuer** [cdaecke/md_fullcalendar#21]
Hello,

when opening the calendar website, I am getting the following error in the console:
```
Uncaught TypeError: e.addClass is not a function
    at t.initialRender (fullcalendar.min.js:10:24016)
    at t.render (fullcalendar.min.js:10:23939)
    at HTMLDocument.<anonymous> (kalender?tx_calendarize_calendar%5Baction%5D=list&tx_calendarize_calendar%5Bcontroller%5D=Calendar&cHash=7fa5609d2c882e669eeb9679bb3ace93:591:29)
```
Typo3: 11.5.25
Calendarize: 12.4.4
md_fullcalendar: 3.0.2
JQuery: 3.6.1

Unfortunately, I have no clue how to debug this issue. I googled this error and it states something related to jquery. But I have no clue how to solve it :-(

**Comment by cdaecke** [comment]
According to the variable `tx_calendarize_calendar` you are not using the extension `ext:md_fullcalendar`. I assume, that you have activated the following constant for `ext:calendarize`:

`plugin.tx_calendarize.settings.useMomentFullCalendarIo = 1`
